kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 8IdtWedt2+7kRqqj3IZsLGg7lHfNnX/olCjfAoeacrY=
      - identity: {}
